version: '3.4'

services:
    app:
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: apivendas-api
        ports:
            - '3333:3333'
        volumes:
            - .:/home/node/app
        environment:
            - PORT=3333
            - APP_SECRET=Minha@Secret@qui
            - APP_API_URL=http://localhost:3333
            - APP_WEB_URL=http://localhost:3000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASS=
            - MAIL_DRIVER=ethereal
            - STORAGE_DRIVER=disk
            - BASE_AVATAR_URL=http://localhost:3333/files
            - AWS_REGION=
            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
        depends_on:
            - db
            - redis
    db:
        build: ./docker/postgres
        container_name: apivendas-db
        restart: always
        tty: true
        ports:
            - '5432:5432'
        volumes:
            - '.docker/dbdata:/var/lib/postgresql/data'
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=apivendas
    redis:
        image: bitnami/redis:latest
        container_name: apivendas-redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    pgadmin:
        image: dpage/pgadmin4
        container_name: apivendas-pgadmin
        tty: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '8000:80'
        depends_on:
            - db
